import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import HeroSect from "./screen/herosect";
import About from "./screen/about";
import logo from "../public/Ricetta-2.ico";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Ricetta || Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <HeroSect />
      <About />
    </>
  );
}
